---
- hosts: 172.31.40.205
  become: yes
  vars:
    myvar1: git
    myvar2: tree
  tasks:
   - name: to displaye variav
     debug:
      msg: "{{myvar1}}"   #given wrng variable and we will ignore this
     tags: skip 
   - name: cjisbv
     debug:
      msg: "{{myvar2}}"
     