---
- hosts: webservers
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: "{{mywebpackonububt}}"
        state: present 
    - name: install ngnix
      apt:
        name: "{{ngnixonubuntu}}"
        state: started