---
- hosts: webservers
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: "{{mywebpackonububt}}"
        state: present 
    - name: start apache2
      service:
         name: "{{mywebpackonububt}}"
         state: started
    